services:
  app:
    env_file: ".env"
    ports: !reset []
    expose:
      - 80
    volumes: !reset ""
  db:
    env_file: ".env"
  pgadmin: !reset ""

networks:
  default:
    name: proxy_host
    external: true
