services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./www
          target: /var/www/html
    environment:
      DATABASE_host: db
      DATABASE_port: 5432
      DATABASE_dbname: db
      DATABASE_user: user
      DATABASE_password: password
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./www:/var/www/html # Mount the local directory to the container
    ports:
      - "8080:80"
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    expose:
      - "5432"
    volumes:
      # - database:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 30

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      # Default email for pgAdmin 4
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      # Password for accessing pgAdmin 4
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
    restart: always
  # mathesar:
  #   image: mathesar/mathesar-prod:latest
  #   depends_on:
  #     - db
  #   ports:
  #     - 8000

volumes:
  pgadmin_data:
    # database:


